sudo: false

language: python

python:
  - '3.8'
env:
  - TOXENV=quality
  - TOXENV=django22
  - TOXENV=django30
  - TOXENV=django31
cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - coveralls

deploy:
  provider: pypi
  user: edx
  password:
    secure: jgyVFcFq9imTV7DRxGk5hy11UAgsaOjPr3xrKg3iQxJXi1w24JJ/0Uvt5yBeuDHFo7IqkZ38bNVWFcpuoS467rFw2JhX5leUD1tpCWQhL59V72Ht5bC5udQ9OGi0tY2HIjpkpUlIh1xYbyKw60iXa4wk7Bt2+gfg+Q48UfBHDc8=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
    condition: $TOXENV = quality
