sudo: false

language: python

python:
  - 2.7
  - 3.5
  - 3.6

env:
  - TOXENV=django111
  - TOXENV=django20
  - TOXENV=django21
  - TOXENV=django22

matrix:
 include:
  - python: 3.6
    env: TOXENV=quality
 exclude:
  - python: 2.7
    env: TOXENV=django20
  - python: 2.7
    env: TOXENV=django21
  - python: 2.7
    env: TOXENV=django22

cache:
    directories:
        - $HOME/.cache/pip

install:
  - pip install coveralls
  - pip install -r test_requirements.txt

script:
  - tox

after_success:
  - coveralls

deploy:
  provider: pypi
  user: edx
  password:
    secure: jgyVFcFq9imTV7DRxGk5hy11UAgsaOjPr3xrKg3iQxJXi1w24JJ/0Uvt5yBeuDHFo7IqkZ38bNVWFcpuoS467rFw2JhX5leUD1tpCWQhL59V72Ht5bC5udQ9OGi0tY2HIjpkpUlIh1xYbyKw60iXa4wk7Bt2+gfg+Q48UfBHDc8=
  distributions: sdist bdist_wheel
  on:
    tags: true
